name: project_1
description: A simple Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
